### ISSUE TITLE
404 Not Found in the first doc example 

### ISSUE THREAD

**Issue by javierarocena** [HarryPeach/kia#8]
Hi, I'm trying the first doc example of kia:

```javascript
import Kia from "https://deno.land/x/kia@0.4.0/mod.ts";

// Just a function to async sleep
function sleep(ms: number) {
	return new Promise((resolve) => setTimeout(resolve, ms));
}

const kia: any = new Kia("I will be back in about 3 seconds");
kia.start();
await sleep(3000) // or any other async action that'll take some time
kia.succeed("Action completed");
```

And console give me this error:

**`error: Import 'https://deno.land/x/kia@0.4.0/mod.ts' failed: 404 Not Found`**

Thanks :)

**Comment by yoroshikun** [comment]
Looks like kia 0.4.0 has been removed from deno.land, 0.3.0 seems to exist so can use that

**Comment by javierarocena** [comment]
Thanks @yoroshikun, its works!

But now I got this weird characters:

--> **ÔêÜ** Action completed

![image](https://user-images.githubusercontent.com/33159867/130213810-ba2a7f31-ada3-4110-a397-539242c966e6.png)

- Windows 10
- Powershell or Bash

Any ideas?

**Comment by yoroshikun** [comment]
Most likely the font being used for your terminal does not have the symbol used for the tick?

**Comment by HarryPeach** [comment]
Not sure why 0.4.0 was removed from deno.land but the new update to 0.4.1 should resolve the original issue anyway if you update your dependencies accordingly :)
